name: Lab4 CI/CD
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: docker compose up -d

      - name: Check start of services
        run: |
          chmod +x ./scripts/wait-script.sh
          chmod +x ./scripts/wait-for.sh
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/local-environment.json
          delayRequest: 1000
          reporters: '[ "cli" ]'

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v

  publish:
    name: Publish services to DockerHub
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Pull docker image to docker registry
        env:
          registry_token: ${{ secrets.REGISTRY_PULL_TOKEN }}
        run: |
          echo $registry_token | docker login -u meekie --password-stdin

          cd ./Gateway
          docker build -t meekie/gateway-service:latest .
          docker push meekie/gateway-service:latest

          cd ..
          cd ./FlightService
          docker build -t meekie/flight-service:latest .
          docker push meekie/flight-service:latest

          cd ..
          cd ./TicketService
          docker build -t meekie/ticket-service:latest .
          docker push meekie/ticket-service:latest

          cd ..
          cd ./BonusService
          docker build -t meekie/bonus-service:latest .
          docker push meekie/bonus-service:latest

  deploy:
    name: Wait for deploy on VK Cloud
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: Wait for deploy
        run: sleep 3m

  run_api_tests:
    name: Run integration tests on VK Cloud
    runs-on: ubuntu-latest
    needs: [ deploy ]
    steps:
      - uses: actions/checkout@v3
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "212.233.96.58 lab4.rsoi.dyusov.com" | sudo tee -a /etc/hosts
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/collection.json
          environment: postman/environment.json
          delayRequest: 3000
          reporters: '[ "cli" ]'